[package]
name = "devpod-provider-exoscale"
description = "DevPod provider for Exoscale Cloud"
version = "0.0.5"
edition = "2021"
authors = ["Hasan Hakkaev <hasan.hakkaev@gmx.at>"]
repository = "https://github.com/hasanhakkaev/devpod-provider-exoscale"
license = "MPL-2.0"
readme = "README.md"
keywords = ["devpod","exoscale"]


[dependencies]
anyhow = { version = "1.0.79", features = [] }
clap = { version = "4.4.11", features = ["derive"] }
exoscale-rs = "2.0.3"
openssh-keys = "0.6.2"
openssl = { version = "0.10.61", features = ["vendored"] }
ssh2 = "0.9.4"
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.6.1", features = ["v4"] }
base64 = { version = "0.21.5", features = [] }
