[package]
name = "devpod-provider-exoscale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = [] }
clap = { version = "4.3.0", features = ["derive"] }
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
exoscale = "2.1.0"
openssh-keys = "0.6.0"
openssl = { version = "0.10.52", features = ["vendored"] }
petname = "1.1.3"
ssh2 = "0.9.4"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
