name: build and release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: devpod-provider-exoscale-linux-arm64
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: devpod-provider-exoscale-linux-amd64
          #
          #          - os_name: Windows-x86_64
          #            os: windows-latest
          #            target: x86_64-pc-windows-msvc
          #            bin: devpod-provider-exoscale-windows-amd64.exe

          #          - os_name: macOS-x86_64
          #            os: macOS-latest
          #            target: x86_64-apple-darwin
          #            bin: devpod-provider-exoscale-darwin-amd64
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: devpod-provider-exoscale-darwin-arm64
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
      - name: rename binary (linux and macos)
        run: mv target/${{ matrix.platform.target }}/release/devpod-provider-exoscale target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: matrix.platform.os_name != 'Windows-x86_64'
      - name: rename binary (windows)
        run: mv target/${{ matrix.platform.target }}/release/devpod-provider-exoscale.exe target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
        if: matrix.platform.os_name == 'Windows-x86_64'
      - name: Generate SHA-256
        run: shasum -a 256 target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} | cut -d ' ' -f 1 > target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
      - name: Upload SHA-256
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Move binaries to release folder
        uses: actions/download-artifact@v4.1.7
        with:
          name: binaries
          path: release
      - name: Compile binaries
        run: |
          chmod +x ./hack/build.sh
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
      - name: Save release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*